#!/usr/bin/python

import roslaunch
import rospy
from topological_map.topological_map import TopologicalMap

if __name__ == '__main__':
    rospy.init_node('topological_map_server', anonymous=True)

    topo_map = TopologicalMap()
    rospy.spin()
