#!/usr/bin/python

import rospy
from networkx_ros.test import TopologicalMap

if __name__ == '__main__':
    rospy.init_node('topological_map', anonymous=True)

    switcher = TopologicalMap('$(find networkx_ros)/config/')


    rospy.spin()
